### ISSUE TITLE
Is TNExT handling merged feeds properly?

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#193] opened 2019-07-10 23:07 UTC
shapefile route export for March 2019 data shows too many trips for SouthWest and Eastern POINT services, as well as multiple start dates.....? @Sihackett

**Comment by PPaulsonOregonDOT** [comment] 2019-07-17 20:17
I think using the most recent GTFS feeds might solve this problem for the eastern point, because I only see two trips represented anywhere in the field, so it would be hard for TNExT to extrapolate that data into multiple runs.

As far as I can tell, this isn't a calendar.txt issue, because I exported the GIS files from the July 2019 database, filtering for 7/17/19, which did not alter the GIS output of the tool.

**Comment by PPaulsonOregonDOT** [comment] 2019-08-07 23:22
People mover provides an oddly differentiated example that might be a could test case for figuring out how erroneous numbers of trips are being generated in the tool. I just ran their GIS routes report from the July 2019 database. In examining, GIS trip generation, most of the routes show the expected number of 2 or three trips. Three trips break this trend, with Prairie City to Burns (Route ID 1858) showing a result of 76 trips, John Day to Baker City Showing 32 trips, and John Day to Canyon City showing 14 trips. These total are reflected in trips.txt of the feed I grabbed on 6/3/19. This suggests to me that this is at least mostly a data error,
[People_Mover_trips.xlsx](https://github.com/ODOT-PTS/TNExT/files/3479221/People_Mover_trips.xlsx)

, and that the tool may be working as intended.

**Comment by ODOT-RPTD-mb** [comment] 2019-08-08 14:29
It is my understanding that there is an open source GTFS merge tool, that one can use to combine GTFS feeds for the same agency, when the state of the network changes, and that Trillium may sometimes use this tool or its GTFS editor support a feed with multiple network states…? 
 
For example agency X has a feed that expires at the end of July, and starting August first there are some stop changes, shape changes, trip changes, route changes, time changes, etc. one can merge the current feed with the future feed so that the transition is seamless for consuming applications….
 
Our hypothesis is that TNExT may not gracefully manage feeds merged in this sense.
 
I have only heard sketchy high level descriptions of this so I may be off base on the details.

**Comment by evantrillium** [comment] 2019-08-08 16:57
> People mover provides an oddly differentiated example that might be a could test case for figuring out how erroneous numbers of trips are being generated in the tool. I just ran their GIS routes report from the July 2019 database. In examining, GIS trip generation, most of the routes show the expected number of 2 or three trips. Three trips break this trend, with Prairie City to Burns (Route ID 1858) showing a result of 76 trips, John Day to Baker City Showing 32 trips, and John Day to Canyon City showing 14 trips. These total are reflected in trips.txt of the feed I grabbed on 6/3/19. This suggests to me that this is at least mostly a data error,
> [People_Mover_trips.xlsx](https://github.com/ODOT-PTS/TNExT/files/3479221/People_Mover_trips.xlsx)
> 
> , and that the tool may be working as intended.

Re: People Mover
Prairie City to Burns and John Day to Baker City both are semi-monthly routes, so the way they get configured in the GTFS is to have them broken out in their own calendar entries with the individual days of service demarcated out. I imagine this may cause issues in how they display.

The John Day to Canyon City is actually an hourly-ish service, so that number of trips is accurate (it's a local route.)

Does that help?

**Comment by anniekfifer** [comment] 2019-09-18 19:13
@ODOT-RPTD-mb @PPaulsonOregonDOT Unless there are other symptoms of this issue it sounds like this may have been resolved by fixing #204, is that the case?

**Comment by PPaulsonOregonDOT** [comment] 2019-09-26 20:07
@anniekfifer, it appears that the tool is no longer combining old feeds in with the new feeds, and you can eliminate trips associated with old service patterns by selecting a specific date, which will provide you with the runs that occur on that date, so I am not seeing any evidence that this issue is still a problem. It might be helpful to have the tool automatically do a date selection based on the current day (which would be more consistent with how the rest of the tool operates), but I think that is best handled through a seperate enhancement request.

**Closed by PPaulsonOregonDOT** 2019-09-26 20:07 UTC
Labels: Importance - HIGH
