### ISSUE TITLE
Null visit Counts

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#180] opened 2019-02-15 21:22 UTC
In the reports that I reviewed for issue #179, I noticed that each of the stop reports returns Null values for each stop in question. I think that we had encountered and resolved this issue recently, but it appears that the new build of the database for January 2019 has reintroduced this in this class of report. For reference

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=101&n=bot&x=0.25&dbindex=13&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=61&n=bot&x=0.25&dbindex=13&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59

**Comment by PPaulsonOregonDOT** [comment] 2019-04-09 22:31
I looking through the statewide stops report, it appears that all but two (the transit agency summary report and the aggregated urban areas summary report) differentiate there stops between urban and rural stops. The stops report for the agency summary report appears to have null values for visits as described above, but the stops  report for the aggregated urban area report does not:

Aggregated Urban Area Report:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasReport.html?&pop=-1&dbindex=15&uc=3&popYear=2010&popMin=0&popMax=2000000&areaid=null&type=-1#

Stops Summary Report for Cottage Grove from the report above:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasReport.html?&pop=-1&dbindex=15&uc=3&popYear=2010&popMin=0&popMax=2000000&areaid=null&type=-1#

**Comment by anniekfifer** [comment] 2019-09-19 22:09
This appears to have something to do with selected/hidden feeds on the main page. The selected/hidden feeds for a user either aren't cached properly or aren't displayed correctly, still trying to figure out how this is supposed to work but there is definitely an inconsistency between selected feeds and the user_selected_agencies table where entries are missing or maybe mistakenly hidden. 

In the meantime there is a workaround that has been working for me -- before running the stops report deselect all feeds, submit, reselect all feeds and submit again. This forces the necessary update to the user_selected_agencies table.

**Comment by anniekfifer** [comment] 2019-10-02 18:51
user_selected_agencies desired behavior: selected/deselected feeds should not persist between sessions

**Comment by anniekfifer** [comment] 2019-10-09 18:12
Note, workaround does not fix for this stop report joined against a geography: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=174&areaid=1&type=4&x=0.25&n=iwt&dbindex=15&rc=0&popYear=2010&geotype=-1&stime=0:00&etime=23:59&geoid=null&nav=stateS-agencyS-regionS

 (from https://github.com/ODOT-PTS/TNExT/issues/164#issuecomment-534332200)

**Comment by anniekfifer** [comment] 2019-10-25 18:33
>user_selected_agencies desired behavior: selected/deselected feeds should not persist between sessions

This is the ideal fix but to me feels like a separate, much more time-consuming issue of implementing actual session tracking, which appears to not be happening currently. 

The actual bug causing this issue is the misrepresentation of data in the selected feeds panel, which will show all feeds selected on first load when that may not reflect what's in the database. This is what I plan to fix for this issue. 

@ODOT-RPTD-mb FYI in case this was unclear, let me know if the solution above isn't sufficient to close this issue.

**Comment by ODOT-RPTD-mb** [comment] 2019-10-25 19:03
@anniekfifer How are we defining a "session"?

Correcting representation of selected feeds in panel will be a significant step forward.

**Comment by anniekfifer** [comment] 2019-10-25 19:48
>@anniekfifer How are we defining a "session"?

A user is bound to a session for a period of time that's usually defined by a specified "max inactive" interval -- i.e. a session ends when the user is inactive for 10 minutes. Sessions can track user actions or session-related data in a way to keep them distinct from other sessions.

It's still unclear to me how sessions are used in tnext, and I take back my earlier comment that they session tracking wasn't "implemented" as that was bad wording, but it does seem like they're not being created or closed properly. I can open a separate issue to investigate that if you'd like but if this is the only bug that might be partially caused by persisting sessions and otherwise they are working properly it might not be a priority.

**Comment by anniekfifer** [comment] 2019-11-04 21:34
There are several different contributing factors that should now be resolved:

- the query for setting hidden/selected feeds had an unnecessary condition that would exclude some agencies hidden status from being tracked, which produced confusing behavior in the UI
- There was nothing initializing the "user selected agencies" for new sessions

There's also a larger issue of inconsistent usage of session/user-tracking methods -- sometimes in the database a username is stored as the unique session id (this is the case with user selected agencies) but there's also a concept of a username, which as far as I can tell is always it's default value "admin". This is relevant to this issue because selected feeds were tracked using the unique session id in the database but the front end would query with the "admin" username. 

As far as I can tell, the concept of a username in this context in tnext should always be unique to a session, and for that reason I've changed the method returning the default "admin" as username to return the session id. I don't think this will affect existing behavior other than correctly tracking selected feeds, but it's hard to say for sure without spending a lot of time digging into all usages. However I'm fairly confident that the method I changed in FileUpload.js is only used for getting selected feeds: https://github.com/ODOT-PTS/TNExT/commit/64443a6b4a80d683cd10e3b9569e2d9b0995648a

**Comment by anniekfifer** [comment] 2019-11-04 21:42
Reopening because I've realized that now that all sessions will be tracking selected feeds in the database, these will pile up and linger in the database and I don't see any way that they are being cleaned up after a session invalidates

**Comment by ODOT-RPTD-mb** [comment] 2020-04-30 20:00
Revisited first report referenced for this issue: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=101&n=bot&x=0.25&dbindex=13&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59 

Initial result had null visit values (60 of 60 agencies selected). After selecting all agencies in filter and re-running report (still 60 of 60 agencies selected), visit values are in place.

Ran this report (58 of 58 agencies selected), null visit values.
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=1&n=cku&x=0.25&dbindex=30&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59

After selecting all agencies in filter and re-running report (still 58 of 58 agencies selected), visit values are in place.

**Comment by anniekfifer** [comment] 2020-05-01 00:44
Ok I think I identified the problem -- new sessions aren't properly initializing  selected agencies. This shouldn't take long to fix

**Closed** 2020-07-09 21:53 UTC
Labels: Importance - VERY HIGH, software
