### ISSUE TITLE
Data w/n TNExT (related - #195 / #193 / #202):  Issue noted when ODOT staff export shapefiles from TNExT -- trips from multiple GTFS feeds appear to be combined, causing # of trips in data file, and database as a whole, to be a multiple of number of trips provided.  Suspect this may be result of feeds inadvertently being imported/carried over from one snapshot to the next, and data from previous feeds combined with data from current GTFS feeds. Solution may be to remove old/obsolete data contained in those database instances and update these within TNExT.

### ISSUE THREAD

**Issue by Sihackett** [ODOT-PTS/TNExT#204] opened 2019-08-21 21:19 UTC

**Comment by anniekfifer** [comment] 2019-08-23 20:08
Hi @Sihackett -- Can you provide us with an example of an export that is affected by this issue, and note the database snapshot that it came from? That would really help us identify the cause.

**Comment by anniekfifer** [comment] 2019-08-23 20:11
@Sihackett Also in your email you referred to documentation from OSU on the admin panel, could you tell me where I could find the full documentation? That could be helpful for my debugging process as well. Thank you!

**Comment by ODOT-RPTD-mb** [comment] 2019-08-26 00:03
Export from Shapefile Generator https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ShapeFileExport.html March 2019 database, Stops, 03/20/2019. Export loaded into QGIS. Image below shows info the Brookings stop. Note the four different effective start dates for each direction of travel. Actual pattern of travel is one daily departure and one daily arrival.

![image](https://user-images.githubusercontent.com/8129162/63657484-83dea700-c757-11e9-8261-665ef6500fe6.png)

**Comment by ODOT-RPTD-mb** [comment] 2019-08-26 13:46
@anniekfifer  When going to agency report https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=45&n=ctt&x=0.25&dbindex=15&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59 and looking at Brookings stop 818197, there is a null value, see issue #180.  When looking for stop 818197 in Curry County report https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&areaid=41015&type=0&x=0.25&n=ctt&dbindex=15&popYear=2010&geotype=-1&geoid=null&rc=1&stime=0:00&etime=23:59&nav=stateS-countyS the visit report for 818197 is 2, which is what is consistent with reality. This implies that the this issue MAY be only impacting shapefiles and not other report types.

**Comment by anniekfifer** [comment] 2019-08-28 23:24
Also let me know what kind of timeline you'd like to see this fixed on staging/production. I'll be out until tuesday starting tomorrow midday, so I probably won't be able to pull a fix into staging until next week unless there's an urgent need

**Comment by anniekfifer** [comment] 2019-08-28 23:43
This is a shapefile for SouthWestPOINT stops exported locally from the March 2019 database with the fix

@ODOT-RPTD-mb @PPaulsonOregonDOT Is someone able to look it over and see if it looks ok? It looks to me like it's not duplicating stop visits

[SouthWestPOINT_stops.zip](https://github.com/ODOT-PTS/TNExT/files/3553221/SouthWestPOINT_stops.zip)

**Comment by PPaulsonOregonDOT** [comment] 2019-08-29 00:14
@anniekfifer. I looked at the file you posted below, and it look reasonable. Did you use the default setting for the report?

**Comment by ODOT-RPTD-mb** [comment] 2019-08-29 00:28
@anniekfifer putting a fix in place next week, work for us.

**Comment by anniekfifer** [comment] 2019-08-29 16:42
>@anniekfifer. I looked at the file you posted below, and it look reasonable. Did you use the default setting for the report?

I believe so, from the shapefile generator I just selected:

- March 2019 database
- SouthWestPOINT 
- Stops
- No date

**Comment by anniekfifer** [comment] 2019-09-06 16:41
I've updated staging with this fix, I'll plan on upgrading production today with this and the fix for #171 shortly after 5pm. Note that there might be a couple minutes of downtime at that time.

**Closed** 2019-09-06 16:41 UTC
Labels: Importance - HIGH

**Comment by anniekfifer** [comment] 2019-09-10 17:21
FYI did not do the production upgrade last week but will plan on doing today after 5pm if I can cherry-pick my changes ok: #207

**Comment by anniekfifer** [comment] 2019-09-13 21:54
Sorry for the delay on this, ran into snags during testing. Will upgrade production today after 5pm unless anyone objects.
